# Generated by Django 5.1 on 2024-11-04 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qr_code',
        ),
        migrations.CreateModel(
            name='WireProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('number_coil', models.CharField(max_length=100)),
                ('initial_length', models.IntegerField(blank=True, null=True)),
                ('total_weight', models.FloatField(blank=True, null=True)),
                ('coil_weight', models.FloatField(blank=True, null=True)),
                ('technical_sheet_photo', models.ImageField(blank=True, null=True, upload_to='products/{id}/')),
                ('wire_created_at', models.DateTimeField(auto_now_add=True)),
                ('wire_modified_at', models.DateTimeField(auto_now=True)),
                ('wire_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand')),
            ],
            options={
                'verbose_name': 'Wire Product',
                'verbose_name_plural': 'Wires Products',
            },
            bases=('products.product',),
        ),
    ]
