# Generated by Django 5.1.1 on 2024-11-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_brand_remove_product_metadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wireproduct',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='wireproduct',
            name='product_ptr',
        ),
        migrations.AddField(
            model_name='product',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='WireProduct',
        ),
    ]
