# Generated by Django 5.1 on 2024-11-13 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_is_active_product_is_active_type_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='metadata',
        ),
        migrations.CreateModel(
            name='SubProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('number_coil', models.PositiveIntegerField(blank=True, null=True)),
                ('initial_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('coil_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('technical_sheet_photo', models.ImageField(blank=True, null=True, upload_to='technical_sheets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subproducts', to='products.product')),
            ],
        ),
    ]
