language: python

workspace: /workspace/InventoryManagementSystem-API

setup:
  - apt-get update
  - apt-get install -y python3 python3-pip gcc libffi-dev python3-dev libjpeg-dev zlib1g-dev netcat-openbsd curl build-essential libjpeg-turbo8-dev postgresql-client
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt

env:
  SECRET_KEY: clave_development_segura
  DJANGO_SETTINGS_MODULE: inventory_management.settings.local
  DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1
  DJANGO_EMAIL_HOST_USER: tu_email@gmail.com
  DJANGO_EMAIL_HOST_PASSWORD: contraseña_segura
  REDIS_HOST: redis
  REDIS_PORT: 6379
  REDIS_URL: redis://redis:6379/0
  CELERY_BROKER_URL: redis://redis:6379/0
  CELERY_RESULT_BACKEND: redis://redis:6379/0
  DJANGO_CORS_ALLOWED_ORIGINS: http://localhost:5173,http://127.0.0.1:5173,http://frontend:5173
  DJANGO_CSRF_TRUSTED_ORIGINS: http://localhost:5173,http://127.0.0.1:5173,http://frontend:5173
  USE_SQLITE: "true"
  PORT: 8000
  OPENAI_API_KEY: sk-proj--...
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minio123
  AWS_PRODUCT_BUCKET_NAME: files-products
  AWS_PROFILE_BUCKET_NAME: img-profiles
  AWS_S3_ENDPOINT_URL: http://minio:9000
  AWS_S3_REGION_NAME: us-east-1
  MINIO_PUBLIC_URL: localhost:9000
  DRIVE_SHARED_SECRET: secreto_desarrollo
  ALLOWED_UPLOAD_EXTENSIONS: .jpg,.jpeg,.png,.webp,.pdf,.mp4,.mov,.avi,.mkv

run:
  - python3 manage.py migrate
  - gunicorn inventory_management.wsgi:application --bind 0.0.0.0:8000
