image: universal

variables:
  PORT: 8000
  SECRET_KEY: tu_secret_key
  DJANGO_SETTINGS_MODULE: config.settings
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_EMAIL_HOST_USER: tu_email@gmail.com
  DJANGO_EMAIL_HOST_PASSWORD: tu_password
  REDIS_HOST: redis
  REDIS_PORT: 6379
  REDIS_URL: redis://redis:6379/0
  CELERY_BROKER_URL: redis://redis:6379/0
  CELERY_RESULT_BACKEND: redis://redis:6379/0
  DJANGO_CORS_ALLOWED_ORIGINS: http://localhost:3000
  DJANGO_CSRF_TRUSTED_ORIGINS: http://localhost:3000
  USE_SQLITE: "True"
  OPENAI_API_KEY: tu_openai_api_key
  AWS_ACCESS_KEY_ID: tu_access_key
  AWS_SECRET_ACCESS_KEY: tu_secret_access
  AWS_PRODUCT_BUCKET_NAME: ims-productos
  AWS_PROFILE_BUCKET_NAME: ims-perfiles
  AWS_S3_ENDPOINT_URL: http://minio:9000
  AWS_S3_REGION_NAME: us-east-1
  MINIO_PUBLIC_URL: http://localhost:9000
  ALLOWED_UPLOAD_EXTENSIONS: ".jpg,.jpeg,.png"

secrets: []

setup:
  - apt-get update
  - apt-get install -y python3 python3-pip gcc libffi-dev python3-dev libjpeg-dev zlib1g-dev netcat-openbsd curl build-essential libjpeg-turbo8-dev postgresql-client
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt

start:
  - python3 manage.py migrate && gunicorn inventory_management.wsgi:application --bind 0.0.0.0:8000
