# Generated by Django 5.1.1 on 2024-10-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuttingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(help_text='Customer name for whom the cutting order is made', max_length=255)),
                ('cutting_quantity', models.DecimalField(decimal_places=2, help_text='Quantity in meters to cut', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_process', 'In Process'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'permissions': [('can_assign_order', 'Can assign a cutting order'), ('can_process_order', 'Can process a cutting order')],
            },
        ),
    ]
