# Generated by Django 5.1.1 on 2024-10-16 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuts', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttingorder',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cutting_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuttingorder',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cutting_operations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuttingorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutting_orders', to='products.product'),
        ),
    ]
