# Generated by Django 5.1.1 on 2024-11-14 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_metadata_subproduct'),
        ('stocks', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si el stock está activo (eliminación suave).'),
        ),
        migrations.AddField(
            model_name='stock',
            name='subproduct',
            field=models.ForeignKey(blank=True, help_text='Referencia opcional al subproducto específico.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='products.subproduct'),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='subproduct',
            field=models.ForeignKey(blank=True, help_text='Subproducto al que se asocia el ajuste de stock, si aplica.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='products.subproduct'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora del último cambio en el stock.'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación.'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Referencia opcional al producto principal.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='products.product'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Cantidad actual de stock.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='stock',
            name='user',
            field=models.ForeignKey(help_text='Usuario que realizó el ajuste de stock.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='change_reason',
            field=models.TextField(help_text='Motivo del ajuste de stock.'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Producto al que se asocia el ajuste de stock.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='products.product'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del ajuste de stock.'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='stock_after',
            field=models.DecimalField(decimal_places=2, help_text='Cantidad de stock después del ajuste.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='stock_before',
            field=models.DecimalField(decimal_places=2, help_text='Cantidad de stock antes del ajuste.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='user',
            field=models.ForeignKey(help_text='Usuario que realizó el ajuste.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
